Improved version update script.

diff --git a/update-pom-versions b/update-pom-versions
--- a/update-pom-versions
+++ b/update-pom-versions
@@ -1,3 +1,7 @@
 #!/bin/bash
-mvn -N versions:update-child-modules
-rm */pom.xml.versionsBackup
+if [ "$1" = "" ]; then
+	echo "$0: ERROR: No version specified."
+	exit 1
+fi
+
+mvn org.codehaus.mojo:versions-maven-plugin:1.2:set -DnewVersion=$1 -DgenerateBackupPoms=false
